import validator.cpf as cpf
import validator.cnpj as cnpj
import validator.cep as cep
import validator.bank_card as bank_card
import validator.date as date
import validator.email as email
import validator.fone_number as fone_number
import validator.passport as passport
import validator.password as password
import validator.url as url
import validator.rg_id as rg_id